### ISSUE TITLE
Persistent InvalidSignature error

### ISSUE THREAD

**Issue by liliserf** [Yelp/yelp-ruby#24]
I've followed everything in the README perfectly and I only get an InvalidSignature whenever I try to make a request. I've reset my keys with Yelp repeatedly and I always get the same error. I am getting my keys from the [manage API access](http://www.yelp.com/developers/manage_api_keys) section of Yelp's site.

Any advice here would be greatly appreciated.

```
irb(main):009:0> client.search("Austin")
Yelp::Error::InvalidSignature: Signature was invalid
    from /home/vagrant/code/mks/final_project/vendor/bundle/gems/yelp-2.0.4/lib/yelp/error.rb:13:in `validate'
    from /home/vagrant/code/mks/final_project/vendor/bundle/gems/yelp-2.0.4/lib/yelp/error.rb:45:in `check_for_error'
    from /home/vagrant/code/mks/final_project/vendor/bundle/gems/yelp-2.0.4/lib/yelp/endpoint/search.rb:167:in `search_request'
    from /home/vagrant/code/mks/final_project/vendor/bundle/gems/yelp-2.0.4/lib/yelp/endpoint/search.rb:47:in `search'
    from /home/vagrant/code/mks/final_project/vendor/bundle/gems/yelp-2.0.4/lib/yelp/client.rb:101:in `public_send'
    from /home/vagrant/code/mks/final_project/vendor/bundle/gems/yelp-2.0.4/lib/yelp/client.rb:101:in `block in add_method'
    from (irb):9
    from /home/vagrant/.rbenv/versions/2.0.0-p481/bin/irb:12:in `<main>'
irb(main):010:0>
```

**Comment by rutgerg** [comment]
I work locally and have this issue. Not sure if and how time could be off. @tomelm suggestions?

**Comment by happysalada** [comment]
Same here, I work locally and have this issue. Any suggestions are welcome
